_commit: 0.0.2rc-210-g3b97536
_src_path: gh:skeleton-ci/skeleton-python
author: bswck
cli: false
copyright: Bartosz Sławecki
description: Install Python packages into volatile memory.
docs: true
email: bartoszpiotrslawecki@gmail.com
github: bswck
license: GPL-3.0
package: mempip
precommit: true
pypi: true
pypi_description: Install Python packages into volatile memory.
pypi_project: mempip
pypy: true
python: '3.8'
python_until: ''
repo: mempip
rtd: mempip
tests: true
tidelift: false
visibility: public
wip: true
